services:
  - type: web
    name: novatrade
    runtime: python
    plan: free
    region: singapore
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.auth_ui:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
